#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Repackage a minimal, MIT-compliant subset of musl 1.1.24 sufficient to build the
# bootstrap tcc, dropping GNU mes libc. Produces musl-1.1.24-subset.tar.gz containing
# exact musl source files (subset), the headers needed to compile them, musl's three
# generated headers (pre-generated for x86_64), our glue, and musl's COPYRIGHT notice.
#
# Usage: ./make-subset-tarball.sh <path-to-musl-1.1.24-source-tree> [output-dir]
set -eu

MUSL=${1:?usage: make-subset-tarball.sh <musl-1.1.24-srcdir> [outdir]}
OUT=${2:-.}
HERE=$(cd "$(dirname "$0")" && pwd)
ARCH=x86_64
NAME=musl-1.1.24-subset
STAGE=$(mktemp -d)
DST=$STAGE/$NAME

mkdir -p "$DST"

# 1. exact subset source files (the 120 from musl-subset.files), plus the per-directory
#    private headers they #include relative to themselves (e.g. src/time/time_impl.h,
#    src/stdio/putc.h, src/errno/__strerror.h, src/multibyte/internal.h).
srcdirs=""
while IFS= read -r f; do
    [ -n "$f" ] || continue
    mkdir -p "$DST/$(dirname "$f")"
    cp "$MUSL/$f" "$DST/$f"
    srcdirs="$srcdirs $(dirname "$f")"
done < "$HERE/musl-subset.files"
for d in $(echo "$srcdirs" | tr ' ' '\n' | sort -u); do
    for h in "$MUSL/$d"/*.h; do
        [ -e "$h" ] && cp "$h" "$DST/$d/"
    done
done

# 2. crt entry C file (crt1.c #includes "crt_arch.h", which ships inside arch/x86_64)
mkdir -p "$DST/crt"
cp "$MUSL/crt/crt1.c" "$DST/crt/crt1.c"

# 3. headers needed to compile the subset (small; trimming headers is not worth it)
for d in include arch/x86_64 arch/generic src/include src/internal; do
    mkdir -p "$DST/$d"
    cp -r "$MUSL/$d/." "$DST/$d/"
done

# 4. musl's three generated headers, pre-generated for x86_64 (no sed/awk at build time)
mkdir -p "$DST/obj/include/bits" "$DST/obj/src/internal"
cp "$HERE/generated/bits/alltypes.h"     "$DST/obj/include/bits/alltypes.h"
cp "$HERE/generated/bits/syscall.h"      "$DST/obj/include/bits/syscall.h"
cp "$HERE/generated/internal/version.h"  "$DST/obj/src/internal/version.h"

# 5. our glue + the file list + the MIT notice
cp -r "$HERE/glue"            "$DST/glue"
cp    "$HERE/musl-subset.files" "$DST/musl-subset.files"
cp    "$MUSL/COPYRIGHT"       "$DST/COPYRIGHT"
cat > "$DST/README" <<EOF
Minimal subset of musl 1.1.24 (MIT licensed; see COPYRIGHT), repackaged to bootstrap
tcc without GNU mes. Exact upstream source files; obj/ holds the three pre-generated
headers for x86_64. glue/ replaces musl's __errno_location, __libc_start_main, and
strtod/strtof/strtold/ldexp (constant-free, for the HAVE_FLOAT=0 stage-1 tcc).
build-libc.kaem compiles the subset into \${LIBDIR}/libc.a with \${CC} (kaem has no
loops, so the per-file command list is generated here). sysinclude.tar is the flat
public-header set to untar into the tcc include dir.
EOF

# 6. build-libc.kaem -- a kaem fragment (kaem has no for-loops) that compiles every
#    subset source + glue into \${O}/*.o with \${CC} and archives \${LIBDIR}/libc.a.
#    Run with cwd = the unpacked subset root; requires CC, O, LIBDIR in the env.
IINC="-nostdinc -I obj/include -I arch/x86_64 -I arch/generic -I obj/src/internal -I src/include -I src/internal -I include"
CFLAGS="-std=c99 -ffreestanding -D_XOPEN_SOURCE=700 -D SYSCALL_NO_TLS"
objname() { echo "$1" | sed 's#/#_#g; s#\.[cs]$#.o#'; }
SRCS=$(grep -vE '^\s*(#|$)' "$HERE/musl-subset.files")
SRCS="$SRCS glue/errno_loc.c glue/start.c glue/sigaction.c glue/float.c"
{
    echo '# Generated by make-subset-tarball.sh -- do not edit.'
    echo '# Compile the musl 1.1.24 subset into ${LIBDIR}/libc.a using ${CC}.'
    echo '# Run with cwd = unpacked subset root. Needs env: CC, O (obj dir), LIBDIR.'
    OBJLIST=""
    for f in $SRCS; do
        o=$(objname "$f")
        echo "\${CC} -c $IINC $CFLAGS $f -o \${O}/$o"
        OBJLIST="$OBJLIST \${O}/$o"
    done
    echo "\${CC} -ar cr \${LIBDIR}/libc.a$OBJLIST"
} > "$DST/build-libc.kaem"

# 7. sysinclude.tar -- flat-merged PUBLIC header set for compiling tcc.c (consumer
#    side). include/ first, then arch/generic/bits, arch/x86_64/bits (arch wins),
#    then the generated obj/include/bits (alltypes.h/syscall.h win). Untar into the
#    tcc include dir; a single -I then resolves every <...> and <bits/...>.
SYS=$(mktemp -d)
( cd "$MUSL/include" && find . -name '*.h' -exec cp --parents {} "$SYS/" \; )
mkdir -p "$SYS/bits"
cp "$MUSL/arch/generic/bits/"*.h "$SYS/bits/"
cp "$MUSL/arch/$ARCH/bits/"*.h   "$SYS/bits/" 2>/dev/null || true
cp "$DST/obj/include/bits/"*.h   "$SYS/bits/"
( cd "$SYS" && tar --format=ustar -cf "$DST/sysinclude.tar" * )
rm -rf "$SYS"

mkdir -p "$OUT"
( cd "$STAGE" && tar -czf "$NAME.tar.gz" "$NAME" )
mv "$STAGE/$NAME.tar.gz" "$OUT/"
rm -rf "$STAGE"
echo "wrote $OUT/$NAME.tar.gz"
