#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
#
# regen.py -- derive the in-chroot `simple-patch` fragments from the canonical
# unified diffs in patches/, and verify each fragment reproduces GNU patch's
# result byte-for-byte.
#
# Why two representations:
#   - patches/*.patch     unified diffs; used where a real `patch` exists (Spack).
#   - simple-patches/*.{before,after}  one fragment pair per hunk; applied in the
#     kaem chain by the repo's `simple-patch` tool (no `patch` in the chroot).
#     `simple-patch FILE before after` replaces the FIRST exact byte-match of
#     `before` with `after`, erroring if absent -- so each fragment carries the
#     hunk's context lines to be a unique anchor.
#
# Some hunks are deliberately NOT turned into fragments:
#   - arch/x86_64/bits/alltypes.h.in (0040): the chroot uses the pre-generated
#     generated/bits/alltypes.h (already in the __musl_va_list_t form), so the
#     .h.in edit is moot in-chroot.
#   - new files created from /dev/null (0040's src/stdarg/va_list.c): shipped as
#     a plain source under newsrc/ and copied into the tree, not patched in.
#
# Usage: regen.py <pristine-musl-srcdir>
#   (re)writes steps/musl-1.1.24/simple-patches/ and newsrc/, then verifies.

import os
import re
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PATCHES = os.path.join(HERE, "patches")
SPDIR = os.path.join(HERE, "simple-patches")
NEWSRC = os.path.join(HERE, "newsrc")

# Files whose hunks we do NOT convert to fragments (handled another way).
SKIP_FILES = {"arch/x86_64/bits/alltypes.h.in"}

HUNK_RE = re.compile(r"^@@ -\d+(?:,(\d+))? \+\d+(?:,(\d+))? @@")


def parse_patch(text):
    """Yield (oldpath, newpath, [hunks]) where each hunk is (before, after).

    before/after are the exact original/patched byte spans for that hunk
    (context + removed -> before; context + added -> after). A hunk whose old
    side is /dev/null is a new file: before == "" signals "create this file".
    """
    files = []
    cur = None
    lines = text.splitlines(keepends=True)
    i = 0
    while i < len(lines):
        line = lines[i]
        if line.startswith("--- "):
            oldp = line[4:].split("\t")[0].strip()
            newp = lines[i + 1][4:].split("\t")[0].strip()
            oldp = oldp[2:] if oldp.startswith(("a/", "b/")) else oldp
            newp = newp[2:] if newp.startswith(("a/", "b/")) else newp
            cur = (oldp, newp, [])
            files.append(cur)
            i += 2
            continue
        m = HUNK_RE.match(line) if cur is not None else None
        if m:
            # Respect the @@ line counts: a hunk consumes exactly old_count
            # (context+removed) and new_count (context+added) lines. Reading
            # past that would slurp the git "-- \n<version>" signature trailer.
            old_left = int(m.group(1)) if m.group(1) is not None else 1
            new_left = int(m.group(2)) if m.group(2) is not None else 1
            before, after = [], []
            i += 1
            while i < len(lines) and (old_left > 0 or new_left > 0):
                h = lines[i]
                if h.startswith("\\"):  # "\ No newline at end of file"
                    i += 1
                    continue
                tag, body = h[0], h[1:]
                if tag == " ":
                    before.append(body); after.append(body)
                    old_left -= 1; new_left -= 1
                elif tag == "-":
                    before.append(body); old_left -= 1
                elif tag == "+":
                    after.append(body); new_left -= 1
                else:
                    break
                i += 1
            cur[2].append(("".join(before), "".join(after)))
            continue
        i += 1
    return files


# Include flags + CFLAGS used to compile every musl object (consumer side uses a
# different, public-only set -- see steps/tcc-0.9.26/pass1.kaem). Kept identical
# to the historical make-subset-tarball.sh so the produced libc.a is unchanged.
IINC = ("-nostdinc -I obj/include -I arch/x86_64 -I arch/generic "
        "-I obj/src/internal -I src/include -I src/internal -I include")
CFLAGS = "-std=c99 -ffreestanding -D_XOPEN_SOURCE=700 -D SYSCALL_NO_TLS"
# Glue compiled into the SUBSET libc only (HAVE_FLOAT=0 / TLS-free crutches).
SUBSET_GLUE = ["glue/errno_loc.c", "glue/start.c", "glue/sigaction.c", "glue/float.c"]


def objname(f):
    return f.replace("/", "_").rsplit(".", 1)[0] + ".o"


def emit_apply(path, frags, header):
    """Write a kaem fragment of `simple-patch` calls (cwd = musl root; ${SP} =
    the simple-patches dir, set by the caller)."""
    with open(path, "w", encoding="utf-8") as f:
        f.write("# %s\n# Generated by regen.py -- do not edit. Needs env: SP.\n" % header)
        for fid, target, _, _ in frags:
            f.write("simple-patch %s ${SP}/%s.before ${SP}/%s.after\n"
                    % (target, fid, fid))


def emit_build_libc(path, srcs, header):
    """Write a kaem fragment compiling `srcs` into ${LIBDIR}/libc.a with ${CC}
    (cwd = musl root; needs env CC, O, LIBDIR)."""
    with open(path, "w", encoding="utf-8") as f:
        f.write("# %s\n# Generated by regen.py -- do not edit. Needs env: CC, O, LIBDIR.\n"
                % header)
        objs = []
        for s in srcs:
            o = objname(s)
            f.write("${CC} -c %s %s %s -o ${O}/%s\n" % (IINC, CFLAGS, s, o))
            objs.append("${O}/" + o)
        f.write("${CC} -ar cr ${LIBDIR}/libc.a" + "".join(" " + o for o in objs) + "\n")


# The SUBSET libc compiles only the 121-file tcc surface, so it needs just these
# three targets patched. Everything else (0006's network hunks, and any full-only
# patch such as sigsetjmp) is FULL-only. apply-full.kaem applies every fragment.
SUBSET_PATCH_TARGETS = {
    "src/internal/syscall.h",      # 0006 (the only 0006 hunk a subset file pulls in)
    "arch/x86_64/syscall_arch.h",  # 0030
    "include/stdarg.h",            # 0040
}


def emit_kaem(fragments, full_files):
    subset_frags = [fr for fr in fragments if fr[1] in SUBSET_PATCH_TARGETS]
    emit_apply(os.path.join(HERE, "apply-subset.kaem"), subset_frags,
               "Apply the tcc-compat musl patches needed for the SUBSET libc.")
    emit_apply(os.path.join(HERE, "apply-full.kaem"), fragments,
               "Apply the tcc-compat musl patches needed for the FULL libc.")

    subset_files = [l.strip() for l in
                    open(os.path.join(HERE, "musl-subset.files"), encoding="utf-8")
                    if l.strip() and not l.lstrip().startswith("#")]
    emit_build_libc(os.path.join(HERE, "build-libc-subset.kaem"),
                    subset_files + SUBSET_GLUE,
                    "Compile the musl 1.1.24 SUBSET (+glue) into libc.a.")

    if full_files is not None:
        emit_build_libc(os.path.join(HERE, "build-libc-full.kaem"), full_files,
                        "Compile FULL musl 1.1.24 (no glue) into libc.a.")
        print("emitted apply-{subset,full}.kaem, build-libc-{subset,full}.kaem")
    else:
        print("emitted apply-{subset,full}.kaem, build-libc-subset.kaem "
              "(full list not supplied -- build-libc-full.kaem left unchanged)")


def main():
    if len(sys.argv) not in (2, 3):
        sys.exit("usage: regen.py <pristine-musl-srcdir> [full.files]")
    musl = sys.argv[1]
    full_files = None
    if len(sys.argv) == 3:
        full_files = [l.strip() for l in open(sys.argv[2], encoding="utf-8")
                      if l.strip()]

    if os.path.isdir(SPDIR):
        shutil.rmtree(SPDIR)
    os.makedirs(SPDIR)
    os.makedirs(NEWSRC, exist_ok=True)

    # id -> (target_path_in_tree, before, after); ordered for in-file order.
    fragments = []
    newfiles = []  # (path_in_tree, content)

    for patchname in sorted(os.listdir(PATCHES)):
        if not patchname.endswith(".patch"):
            continue
        num = patchname.split("-")[0]
        text = open(os.path.join(PATCHES, patchname), encoding="utf-8").read()
        for oldp, newp, hunks in parse_patch(text):
            if oldp == "/dev/null":
                # new file: single hunk, all '+' lines
                newfiles.append((newp, hunks[0][1]))
                continue
            if oldp in SKIP_FILES:
                continue
            for hi, (before, after) in enumerate(hunks):
                fid = "%s_%s_%02d" % (num, oldp.replace("/", "_"), hi)
                fragments.append((fid, oldp, before, after))

    # write fragments + new files
    for fid, target, before, after in fragments:
        open(os.path.join(SPDIR, fid + ".before"), "w", encoding="utf-8").write(before)
        open(os.path.join(SPDIR, fid + ".after"), "w", encoding="utf-8").write(after)
    for path, content in newfiles:
        dst = os.path.join(NEWSRC, path)
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        open(dst, "w", encoding="utf-8").write(content)

    # write a manifest: fid <space> target  (consumed when emitting apply kaem)
    with open(os.path.join(SPDIR, "MANIFEST"), "w", encoding="utf-8") as f:
        for fid, target, _, _ in fragments:
            f.write("%s %s\n" % (fid, target))

    print("wrote %d fragment pairs, %d new files" % (len(fragments), len(newfiles)))

    emit_kaem(fragments, full_files)

    # ---- verify: simple-patch(pristine_file) == patch(pristine_file) ----
    # Build the reference (GNU patch) tree once.
    import tempfile
    ref = tempfile.mkdtemp()
    shutil.copytree(musl, os.path.join(ref, "m"))
    refm = os.path.join(ref, "m")
    for patchname in sorted(os.listdir(PATCHES)):
        if patchname.endswith(".patch"):
            subprocess.run(["patch", "-p1", "--no-backup-if-mismatch", "-i",
                            os.path.join(PATCHES, patchname)],
                           cwd=refm, check=True, stdout=subprocess.DEVNULL)

    # Apply fragments to fresh pristine copies, grouping by target file, in order.
    from collections import OrderedDict
    byfile = OrderedDict()
    for fid, target, before, after in fragments:
        byfile.setdefault(target, []).append((before, after))

    failures = 0
    for target, frags in byfile.items():
        orig = open(os.path.join(musl, target), encoding="utf-8").read()
        buf = orig
        for before, after in frags:
            idx = buf.find(before)
            if idx < 0:
                print("  FAIL %s: before-fragment not found" % target)
                failures += 1
                break
            buf = buf[:idx] + after + buf[idx + len(before):]
        if target in SKIP_FILES:
            continue
        refp = os.path.join(refm, target)
        want = open(refp, encoding="utf-8").read() if os.path.exists(refp) else orig
        if buf != want:
            print("  FAIL %s: simple-patch result != patch result" % target)
            failures += 1
        else:
            print("  ok   %s (%d hunk(s))" % (target, len(frags)))
    shutil.rmtree(ref)
    if failures:
        sys.exit("VERIFY FAILED: %d file(s)" % failures)
    print("verify OK")


if __name__ == "__main__":
    main()
