#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Build a single shell-phase package as its own process tree, invoked by a
# dag.mk recipe (generated by script-generator). PATH is composed by the recipe
# from the package's dependency closure + BASEPATH, so this script must NOT
# recompose it (env deliberately leaves PATH untouched). Stamps live in
# /steps/stamps; the recipe also touches the stamp, this is belt-and-braces.
set -e

pkg=$1
pass=${2:-1}

cd /steps
. ./bootstrap.cfg
. ./env
. ./helpers.sh

# Shell-phase exports that the build subprocesses (configure/make/cc) need.
# These used to live in improve/update_env.sh; the PATH glob it also carried is
# gone (the recipe sets PATH). Each package builds in its own process, so these
# must be (re)exported here rather than inherited from one long-lived shell.
export HOME=/tmp
export SOURCE_DATE_EPOCH=0
export SHELL=/bin/sh
export PATH

build "${pkg}" "pass${pass}.sh"

# Install the declared direct deps into the prefix as .deps -- the seed of a
# future `spack reindex` (store node = dir name, edges = .deps). See DAG.md.
if [ -f "/steps/${pkg}/deps" ]; then
    cp "/steps/${pkg}/deps" "${PKGDIR}/${pkg}/.deps"
fi

mkdir -p /steps/stamps
touch "/steps/stamps/${pkg}"
