#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Shell-phase build orchestration (see DAG.md).
#
# The kaem phase (tcc-0.9.26 -> musl -> tcc-0.9.27 -> ... -> dash) is inherently
# sequential and is built by 0.sh. By the time we get here we have a real POSIX
# environment -- dash, coreutils, sed, make-3.82 -- so the shell-phase build
# graph is computed in plain shell rather than in the primitive-C
# script-generator. script-generator hands us two ordered package lists:
#
#   /steps/base-packages   kaem-phase packages (the implicit base layer)
#   /steps/shell-packages  shell-phase packages (the DAG nodes)
#
# From those plus each package's steps/<name>/deps file we:
#   1. compose BASEPATH (the base layer, newest-first, then the seed prefixes),
#   2. compute each package's transitive dependency closure,
#   3. emit /steps/dag.mk (one stamp target per package, per-package PATH),
#   4. run it under make -- two stages, because make-3.82 is the only scheduler
#      available at shell-phase start and we do not trust it with -j.
#
# Tools available here: dash + coreutils + sed only. grep/gawk/m4 are themselves
# the first shell-phase packages, so this script must not use them.
set -e

cd /steps
. ./bootstrap.cfg
. ./env

STAMPS=/steps/stamps
LOGS=/steps/logs
CLO=/steps/closure
MK=/steps/dag.mk

rm -rf "${CLO}"
mkdir -p "${STAMPS}" "${LOGS}" "${CLO}"

# Read the package lists into space-separated strings (manifest order).
BASE=$(cat /steps/base-packages)
SHELL_PKGS=$(cat /steps/shell-packages)
ALL="${BASE} ${SHELL_PKGS}"

# member <item> <set...> : is <item> one of the remaining words?
member() {
    needle=$1
    shift
    for w in "$@"; do
        if [ "${w}" = "${needle}" ]; then
            return 0
        fi
    done
    return 1
}

# Read a package's direct deps (one name-version per line, # comments, blanks
# allowed) into a space-separated string.
read_deps() {
    f="/steps/$1/deps"
    out=""
    [ -f "${f}" ] || { printf '%s' ""; return; }
    while IFS= read -r line || [ -n "${line}" ]; do
        line=${line%%#*}            # strip trailing comment
        for tok in ${line}; do      # word-split; skips blank lines
            out="${out} ${tok}"
            break                   # one package per line
        done
    done < "${f}"
    printf '%s' "${out}"
}

# BASEPATH: the base layer (kaem /opt prefixes) newest-first, then the seed
# prefixes. Replaces the runtime /opt/*/bin glob the old update_env.sh used.
BASEPATH=""
for p in ${BASE}; do
    BASEPATH="/opt/${p}/bin:${BASEPATH}"   # prepend -> reverse (newest first)
done
BASEPATH="${BASEPATH}${SEED_PATH}"

# Compute the transitive closure of every shell-phase package. Manifest order is
# a topological order, so a single forward pass suffices: a dep is always an
# earlier package whose closure is already on disk. "seen" is every package
# before the current one -- used to enforce the earlier-in-manifest rule.
seen=""
for p in ${ALL}; do
    if member "${p}" ${SHELL_PKGS}; then
        deps=$(read_deps "${p}")
        clo=""
        for d in ${deps}; do
            if ! member "${d}" ${seen}; then
                echo "deps: ${p} depends on '${d}' which is unknown or not earlier in the manifest" >&2
                exit 1
            fi
            member "${d}" ${clo} || clo="${clo} ${d}"
            if [ -f "${CLO}/${d}" ]; then
                for e in $(cat "${CLO}/${d}"); do
                    member "${e}" ${clo} || clo="${clo} ${e}"
                done
            fi
        done
        printf '%s\n' "${clo}" > "${CLO}/${p}"
    fi
    seen="${seen} ${p}"
done

# ALL reversed (descending manifest index) -- the order PATH closure members are
# emitted in: most-derived first.
ALL_REV=""
for p in ${ALL}; do
    ALL_REV="${p} ${ALL_REV}"
done

# Emit dag.mk.
{
    echo "# Generated by build-dag.sh from steps/manifest + steps/*/deps."
    echo "SHELL := /bin/sh"
    echo "S := ${STAMPS}"
    echo "L := ${LOGS}"
    printf 'BASEPATH := %s\n\n' "${BASEPATH}"
    echo ".PHONY: all"
    printf 'all:'
    for p in ${SHELL_PKGS}; do
        printf ' $(S)/%s' "${p}"
    done
    printf '\n\n'
} > "${MK}"

for p in ${SHELL_PKGS}; do
    deps=$(read_deps "${p}")
    clo=$(cat "${CLO}/${p}")

    # Target + direct-dep prerequisites (make handles transitivity). Base-layer
    # deps have pre-touched stamps (below); shell deps are built by their rule.
    printf '$(S)/%s:' "${p}" >> "${MK}"
    for d in ${deps}; do
        printf ' $(S)/%s' "${d}" >> "${MK}"
    done
    printf '\n' >> "${MK}"

    # PATH = own prefix, then closure members (descending manifest index), then
    # BASEPATH. Deterministic; no runtime composition.
    rule_path="/opt/${p}/bin:"
    for q in ${ALL_REV}; do
        if member "${q}" ${clo}; then
            rule_path="${rule_path}/opt/${q}/bin:"
        fi
    done

    # Recipe: '+' so MAKEFLAGS (jobserver) reaches the inner make; one log per
    # package so -jN stdout does not interleave; on failure tail the log + stop.
    printf '\t+@echo "=> %s"; \\\n' "${p}" >> "${MK}"
    printf '\tPATH=%s$(BASEPATH) \\\n' "${rule_path}" >> "${MK}"
    printf '\t  sh /steps/build-one.sh %s 1 >$(L)/%s.log 2>&1 \\\n' "${p}" "${p}" >> "${MK}"
    printf '\t  || { echo "!! %s FAILED, tail of $(L)/%s.log:"; tail -n 40 $(L)/%s.log; exit 1; }\n' "${p}" "${p}" "${p}" >> "${MK}"
    printf '\t@touch $@\n\n' >> "${MK}"
done

# Pre-stamp the base-layer packages 0.sh already built.
for p in ${BASE}; do
    touch "${STAMPS}/${p}"
done

# Find the make-4.x bootstrap package: it splits the two stages.
make_new=""
for p in ${SHELL_PKGS}; do
    case "${p}" in
        make-4*) make_new=${p}; break ;;
    esac
done

# Stage 1: bring up make-4.x with the only scheduler we have (make-3.82),
# serially -- its parallel races are the reason make-4.x exists. Stage 2: the
# rest, parallel, under make-4.x's robust fifo jobserver.
PATH="${BASEPATH}"
export PATH
if [ -n "${make_new}" ]; then
    make -f "${MK}" "${STAMPS}/${make_new}"
    PATH="/opt/${make_new}/bin:${BASEPATH}"
    export PATH
fi
exec make -f "${MK}" -j"${JOBS}" all
